// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-cycles.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_cycles_default = defineTool({
  name: "list_cycles",
  title: "List OKR cycles",
  description: "List OKR cycles visible to the signed-in user (respects Business Unit scope).",
  inputSchema: {
    status: z.enum(["draft", "active", "closed"]).optional().describe("Optional cycle status filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb(ctx).from("cycles").select("id,name,status,start_date,end_date,business_unit_id,locked").order("start_date", { ascending: false });
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { cycles: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-objectives.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_objectives_default = defineTool2({
  name: "list_objectives",
  title: "List objectives",
  description: "List OKR objectives the signed-in user can see. Filter by cycle and/or owner.",
  inputSchema: {
    cycle_id: z2.string().uuid().optional(),
    owner_id: z2.string().uuid().optional().describe("Filter to objectives owned by this user."),
    only_mine: z2.boolean().optional().describe("Only objectives owned by the caller.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ cycle_id, owner_id, only_mine }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb2(ctx).from("objectives").select("id,title,description,progress,owner_id,cycle_id,parent_objective_id,business_unit_id,created_at").order("created_at", { ascending: false });
    if (cycle_id) q = q.eq("cycle_id", cycle_id);
    if (only_mine) q = q.eq("owner_id", ctx.getUserId());
    else if (owner_id) q = q.eq("owner_id", owner_id);
    const { data, error } = await q;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { objectives: data ?? [] } };
  }
});

// src/lib/mcp/tools/get-objective.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_objective_default = defineTool3({
  name: "get_objective",
  title: "Get objective with KRs",
  description: "Fetch a single objective by id together with its key results and immediate child objectives.",
  inputSchema: { objective_id: z3.string().uuid() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ objective_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb3(ctx);
    const [{ data: objective, error: e1 }, { data: krs, error: e2 }, { data: children, error: e3 }] = await Promise.all([
      client.from("objectives").select("*").eq("id", objective_id).maybeSingle(),
      client.from("key_results").select("id,title,current_value,start_value,target_value,unit,weight,owner_id,due_date").eq("objective_id", objective_id),
      client.from("objectives").select("id,title,progress,owner_id").eq("parent_objective_id", objective_id)
    ]);
    const err = e1 || e2 || e3;
    if (err) return { content: [{ type: "text", text: err.message }], isError: true };
    if (!objective) return { content: [{ type: "text", text: "Objective not found or not visible" }], isError: true };
    const payload = { objective, key_results: krs ?? [], child_objectives: children ?? [] };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/tools/list-initiatives.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_initiatives_default = defineTool4({
  name: "list_initiatives",
  title: "List initiatives",
  description: "List initiatives visible to the signed-in user. Filter by cycle, owner, or completion state.",
  inputSchema: {
    cycle_id: z4.string().uuid().optional(),
    owner_id: z4.string().uuid().optional(),
    only_mine: z4.boolean().optional(),
    completed: z4.boolean().optional().describe("If true, only completed initiatives; if false, only open ones.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ cycle_id, owner_id, only_mine, completed }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb4(ctx).from("initiatives").select("id,title,description,owner_id,cycle_id,business_unit_id,deadline,status,channel,created_at").order("deadline", { ascending: true });
    if (cycle_id) q = q.eq("cycle_id", cycle_id);
    if (only_mine) q = q.eq("owner_id", ctx.getUserId());
    else if (owner_id) q = q.eq("owner_id", owner_id);
    if (completed === true) q = q.in("status", ["completed", "completed_late"]);
    else if (completed === false) q = q.eq("status", "pending");
    const { data, error } = await q;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { initiatives: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-kr-checkin.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^3.25.76";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_kr_checkin_default = defineTool5({
  name: "create_kr_checkin",
  title: "Create key result check-in",
  description: "Register a check-in on a key result with the current value. Progress propagates to the parent objectives.",
  inputSchema: {
    key_result_id: z5.string().uuid(),
    value: z5.number().describe("New current value for the key result."),
    sentiment: z5.enum(["on_track", "at_risk", "off_track"]).optional(),
    impediments: z5.string().optional(),
    comment: z5.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ key_result_id, value, sentiment, impediments, comment }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const payload = {
      key_result_id,
      value,
      user_id: ctx.getUserId()
    };
    if (sentiment) payload.sentiment = sentiment;
    if (impediments) payload.impediments = impediments;
    if (comment) payload.comment = comment;
    const { data, error } = await sb5(ctx).from("kr_checkins").insert(payload).select().maybeSingle();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { checkin: data } };
  }
});

// src/lib/mcp/tools/whoami.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
function sb6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool6({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's profile, roles, and Business Units.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb6(ctx);
    const uid = ctx.getUserId();
    const [{ data: profile }, { data: roles }, { data: bus }] = await Promise.all([
      client.from("profiles").select("id,email,full_name,job_title,department,management").eq("id", uid).maybeSingle(),
      client.from("user_roles").select("role").eq("user_id", uid),
      client.from("user_business_units").select("business_unit_id,business_units(name)").eq("user_id", uid)
    ]);
    const payload = {
      user_id: uid,
      email: ctx.getUserEmail(),
      profile,
      roles: (roles ?? []).map((r) => r.role),
      business_units: bus ?? []
    };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hmvipnpfejduneusoekn";
var mcp_default = defineMcp({
  name: "vektorflow-mcp",
  title: "Vektor Flow MCP",
  version: "0.1.0",
  instructions: "Tools to explore and update OKRs and initiatives in Vektor Flow. All access respects the signed-in user's roles and Business Unit scope (RLS). Use `whoami` to inspect the current user, `list_cycles`, `list_objectives`, `get_objective`, `list_initiatives` to read data, and `create_kr_checkin` to register progress on a key result.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_cycles_default,
    list_objectives_default,
    get_objective_default,
    list_initiatives_default,
    create_kr_checkin_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
